micronaut:
  application:
    name: registraChavePixGrpc


grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://localhost:3306/registraPix?createDatabaseIfNotExist=TRUE&useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:ot}
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa.default.properties.hibernate.hbm2ddl.auto: update

# API CLIENT REST
url_consulta_itau: ${URL_CONSULTA_CLIENTE_ITAU:`http://localhost:9091/api/v1/clientes`}
